name: Ecommerce Code Checker

on:
  - pull_request
  - push

jobs:
  Ecommerce:
    name: Ecommerce Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['>=18.0.0 <=18.16.0']
    steps:
      - name: Checkout Code ðŸ“¥
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache dependencies ðŸš€
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            ./node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Project Dependencies âœ…
        run: yarn workspace:setup


      - name: Run Build
        run: yarn build
